export type CardProps = {
  id: number;
  categories: string[];
  title: string;
  imageUrl: string;
};
export const db: CardProps[] = [
  {
    id: 0,
    categories: ["urodziny"],
    title: "Tort Na Moją Osiemnastkę",
    imageUrl: "https://i.ibb.co/Ky5N1fV/ewa.jpg",
  },
  {
    id: 1,
    categories: ["rocznica"],
    title: "Tort na rocznice ślubu",
    imageUrl: "https://i.ibb.co/sgxPRz8/oplatek1.jpg",
  },
  // {
  //   id: 2,
  //   categories: ["owocowy"],
  //   title: "Tort owocowy",
  //   imageUrl: "https://i.ibb.co/S60RNHy/owocowe1.jpg",
  // },
  {
    id: 3,
    categories: ["sport"],
    title: "Tort dla tenisisty stołowego",
    imageUrl: "https://i.ibb.co/h9Kxv48/pingpong1.jpg",
  },
  {
    id: 4,
    categories: ["dzieci", "zwierzęta"],
    title: "Tort dla fana ptaszków nr 1",
    imageUrl: "https://i.ibb.co/6gP2mBR/ptaszki1.jpg",
  },
  {
    id: 5,
    categories: ["zwierzęta", "nietypowy"],
    title: "Tort dla łowcy",
    imageUrl: "https://i.ibb.co/q1r77qJ/lowiecki1.jpg",
  },
  {
    id: 6,
    categories: ["czekoladki"],
    title: "Tort czekoladkowy nr 1",
    imageUrl: "https://i.ibb.co/G5hDdhc/czekoladki1.jpg",
  },
  {
    id: 7,
    categories: ["urodziny"],
    title: "Tort dla Dżentelmena nr 1",
    imageUrl: "https://i.ibb.co/T08NW00/dzentelmen1.jpg",
  },
  {
    id: 8,
    categories: ["urodziny", "nietypowy"],
    title: "Tort dla fana piwa Tyskie",
    imageUrl: "https://i.ibb.co/NSmQTMM/piwo1.jpg",
  },
  {
    id: 9,
    categories: ["urodziny", "dzieci", "zwierzęta"],
    title: "Tort Świnka nr 1",
    imageUrl: "https://i.ibb.co/TBDz4Fh/swinka1.jpg",
  },
  {
    id: 10,
    categories: ["urodziny", "rocznica"],
    title: "Tort dla Czterdziestolatki",
    imageUrl: "https://i.ibb.co/qnjcdFZ/tort40.jpg",
  },
  {
    id: 11,
    categories: ["dzieci", "sport"],
    title: "Tort dla Piłkarza",
    imageUrl: "https://i.ibb.co/02yZww2/pilkarski1.jpg",
  },
  {
    id: 12,
    categories: ["czekoladki"],
    title: "Tort Czekoladkowy nr 2",
    imageUrl: "https://i.ibb.co/Rz15MHB/czekoladki2.jpg",
  },
  {
    id: 13,
    categories: ["gracz", "dzieci"],
    title: "Tort Minecraft",
    imageUrl: "https://i.ibb.co/DD9RGTB/minecraft1.jpg",
  },
  {
    id: 14,
    categories: ["urodziny", "rocznica"],
    title: "Tort Owocowy",
    imageUrl: "https://i.ibb.co/XLWNHCJ/owocowy2.jpg",
  },
  {
    id: 15,
    categories: ["urodziny", "czekoladki"],
    title: "Tort na Osiemnastkę",
    imageUrl: "https://i.ibb.co/wLPfWnT/tort18.jpg",
  },
  {
    id: 16,
    categories: ["dzieci", "gracz"],
    title: "Tort Gracza nr 2",
    imageUrl: "https://i.ibb.co/h8vz3Nd/gracza2.jpg",
  },
  {
    id: 17,
    categories: ["dzieci"],
    title: "Tort ze Słodyczy",
    imageUrl: "https://i.ibb.co/jwcLN9d/michasia.jpg",
  },
  {
    id: 18,
    categories: ["urodziny"],
    title: "Tort Dla Solenizantki nr 1",
    imageUrl: "https://i.ibb.co/BnkYNBb/frida.jpg",
  },
  {
    id: 19,
    categories: ["dzieci", "gracz"],
    title: "Tort Gracza nr 3",
    imageUrl: "https://i.ibb.co/bXBj39F/gracza3.jpg",
  },
  {
    id: 20,
    categories: ["urodziny"],
    title: "Tort Czekoladkowy nr 3",
    imageUrl: "https://i.ibb.co/5hT4WcS/czekoladki3.jpg",
  },
  {
    id: 21,
    categories: ["dzieci", "nietypowy", "zwierzęta"],
    title: "Tort Świnka nr 2",
    imageUrl: "https://i.ibb.co/7jZLzgm/swinka2.jpg",
  },
  {
    id: 22,
    categories: ["dzieci"],
    title: "Tort Czerwonego Kapturka",
    imageUrl: "https://i.ibb.co/4R4GSTW/kapturek.jpg",
  },
  {
    id: 23,
    categories: ["zwierzęta"],
    title: "Tort dla fana ptaszków nr 2",
    imageUrl: "https://i.ibb.co/rF48C0j/ptaszki2.jpg",
  },
  {
    id: 24,
    categories: ["urodziny"],
    title: "Tort Urodzinowy nr 1",
    imageUrl: "https://i.ibb.co/1ZyBSPP/urodziny-Nr1.jpg",
  },
  {
    id: 25,
    categories: ["dzieci", "gracz"],
    title: "Tort Gracza nr 4",
    imageUrl: "https://i.ibb.co/HN9YSLc/gracza4.jpg",
  },
  // {
  //   id: 26,
  //   categories: ["dzieci", "gracz"],
  //   title: "Tort Gracza nr 4",
  //   imageUrl: "https://i.ibb.co/HN9YSLc/gracza4.jpg",
  // },
  {
    id: 27,
    categories: ["urodziny"],
    title: "Tort Czekoladkowy nr 4",
    imageUrl: "https://i.ibb.co/h9P1sGj/czekoladki4.jpg",
  },
  {
    id: 28,
    categories: ["urodziny", "nietypowy"],
    title: "Tort Pistacjowy nr 1",
    imageUrl: "https://i.ibb.co/55JCvX0/pistacjowy1.jpg",
  },
  {
    id: 29,
    categories: ["gracz", "dzieci", "nietypowy"],
    title: "Tort Pokemon",
    imageUrl: "https://i.ibb.co/9wHx6gR/pokemon.jpg",
  },
  {
    id: 30,
    categories: ["dzieci"],
    title: "Tort Monster High",
    imageUrl: "https://i.ibb.co/QJ3bR3s/monsterhigh1.jpg",
  },
  {
    id: 31,
    categories: ["urodziny"],
    title: "Tort dla Dżentelmena nr 2",
    imageUrl: "https://i.ibb.co/y5r2pb0/dzentelmen2.jpg",
  },
  {
    id: 32,
    categories: ["urodziny", "nietypowy"],
    title: "Tort Budowlańca",
    imageUrl: "https://i.ibb.co/2c8mfBp/budowlaniec1.jpg",
  },
  {
    id: 33,
    categories: ["urodziny"],
    title: "Tort Dżentelmena nr 3",
    imageUrl: "https://i.ibb.co/bsZ7BHN/dzentelmen3.jpg",
  },
  {
    id: 34,
    categories: ["urodziny"],
    title: "Tort Czekoladowy nr 1",
    imageUrl: "https://i.ibb.co/MMySxjd/czekoladowy1.jpg",
  },
  {
    id: 35,
    categories: ["rocznica"],
    title: "Tort Dla Solenizantki nr 2",
    imageUrl: "https://i.ibb.co/fqH5ChK/tort18-2.jpg",
  },
  {
    id: 36,
    categories: ["dzieci"],
    title: "Tort z Bajki nr 1",
    imageUrl: "https://i.ibb.co/25s4gL3/sing.jpg",
  },
  {
    id: 37,
    categories: ["dzieci"],
    title: "Tort Gracza nr 5",
    imageUrl: "https://i.ibb.co/vwfnzdK/spiderman1.jpg",
  },
  {
    id: 38,
    categories: ["dzieci"],
    title: "Tort Czekoladkowy nr 5",
    imageUrl: "https://i.ibb.co/wp9hhzb/czekoladki5.jpg",
  },
  {
    id: 39,
    categories: ["rocznica"],
    title: "Tort Oreo nr 1",
    imageUrl: "https://i.ibb.co/BCrQdTN/oreo1.jpg",
  },
  {
    id: 40,
    categories: ["rocznica", "nietypowy"],
    title: "Tort Lekarki nr 1",
    imageUrl: "https://i.ibb.co/RTbr7ht/lekarka1.jpg",
  },
  {
    id: 41,
    categories: ["urodziny", "nietypowy"],
    title: "Tort Rolnika",
    imageUrl: "https://i.ibb.co/4dCrrDc/traktor.jpg",
  },
  {
    id: 42,
    categories: ["urodziny", "dzieci", "zwierzęta"],
    title: "Tort Świnka nr 3",
    imageUrl: "https://i.ibb.co/PcFMghS/swinka3.jpg",
  },
  {
    id: 43,
    categories: ["dzieci"],
    title: "Tort Farma",
    imageUrl: "https://i.ibb.co/kh9hBkt/farma.jpg",
  },
  {
    id: 44,
    categories: ["nietypowy"],
    title: "Tort Dla Kucharza",
    imageUrl: "https://i.ibb.co/bHy2F90/garnek.jpg",
  },
  {
    id: 45,
    categories: ["urodziny"],
    title: "Tort Kremowy nr 1",
    imageUrl: "https://i.ibb.co/4tVWMzR/kremowy1.jpg",
  },
  {
    id: 46,
    categories: ["zwierzęta"],
    title: "Tort z Koniem",
    imageUrl: "https://i.ibb.co/7rGNZyw/kon1.jpg",
  },
  {
    id: 47,
    categories: ["dzieci", "nietypowy"],
    title: "Tort Lego",
    imageUrl: "https://i.ibb.co/jZKC2X3/lego1.jpg",
  },
  {
    id: 48,
    categories: ["rocznica"],
    title: "Tort Kremowy nr 2",
    imageUrl: "https://i.ibb.co/988bw5Y/kremowy2.jpg",
  },
  {
    id: 49,
    categories: ["urodziny", "sport"],
    title: "Tort Piłkarski nr 2",
    imageUrl: "https://i.ibb.co/0yBbVjN/pilkarski2.jpg",
  },
  {
    id: 50,
    categories: ["gracz", "dzieci"],
    title: "Tort Fortnite",
    imageUrl: "https://i.ibb.co/L16f6mP/gracza5.jpg",
  },
  {
    id: 51,
    categories: ["dzieci"],
    title: "Tort Z Króliczkiem",
    imageUrl: "https://i.ibb.co/Gdp7Q8d/kroliczek1.jpg",
  },
  {
    id: 52,
    categories: ["urodziny"],
    title: "Tort Oreo nr 2",
    imageUrl: "https://i.ibb.co/7jrkQ0G/oreo2.jpg",
  },
  {
    id: 53,
    categories: ["urodziny"],
    title: "Tort Kremowy nr 3",
    imageUrl: "https://i.ibb.co/jrvyHbb/kremowy3.jpg",
  },
  {
    id: 54,
    categories: ["dzieci"],
    title: "Tort Zajączek",
    imageUrl: "https://i.ibb.co/fQ1tKpH/zajaczek.jpg",
  },
  {
    id: 55,
    categories: ["rocznica", "nietypowy"],
    title: "Tort JagerMeister",
    imageUrl: "https://i.ibb.co/Qms1jVJ/jager1.jpg",
  },
  {
    id: 56,
    categories: ["urodziny", "nietypowy"],
    title: "Tort dla Muzyka",
    imageUrl: "https://i.ibb.co/hC5Nscp/muzyk1.jpg",
  },
  {
    id: 57,
    categories: ["nietypowy"],
    title: "Tort Johnie Walker",
    imageUrl: "https://i.ibb.co/XtxvcpR/walker.jpg",
  },
  {
    id: 58,
    categories: ["nietypowy", "dzieci"],
    title: "Tort z Gwiezdnych Wojen",
    imageUrl: "https://i.ibb.co/GMsRr9P/starwars.jpg",
  },
  {
    id: 59,
    categories: ["dzieci"],
    title: "Tort z Bajki Auta",
    imageUrl: "https://i.ibb.co/ZX6dsyC/auta.jpg",
  },
  {
    id: 60,
    categories: ["dzieci"],
    title: "Tort z Harrego Pottera nr 1",
    imageUrl: "https://i.ibb.co/r32x7Hb/harryp.jpg",
  },
  {
    id: 61,
    categories: ["sport"],
    title: "Tort Piłkarski nr 3",
    imageUrl: "https://i.ibb.co/JvgR1g1/pilkarski3.jpg",
  },
  {
    id: 62,
    categories: ["dzieci", "gracz"],
    title: "Tort Gracza nr 6",
    imageUrl: "https://i.ibb.co/c8VYDhW/roblox.jpg",
  },
  {
    id: 63,
    categories: ["dzieci", "gracz"],
    title: "Tort - Strażak Sam",
    imageUrl: "https://i.ibb.co/xqkdwFx/strazak.jpg",
  },
  {
    id: 64,
    categories: ["dzieci", "gracz"],
    title: "Tort z gry Chicken Gun",
    imageUrl: "https://i.ibb.co/6Jqmsdz/chickengun.jpg",
  },
  {
    id: 65,
    categories: ["urodziny"],
    title: "Tort Kremowy nr 4",
    imageUrl: "https://i.ibb.co/L8Y6ZpS/kremowy4.jpg",
  },
  {
    id: 66,
    categories: ["dzieci"],
    title: "Tort z Harrego Pottera nr 2",
    imageUrl: "https://i.ibb.co/rmsy6gT/harryp2.jpg",
  },
];
