export const db = [
  {
    id: 0,
    category: ["urodziny"],
    title: "Tort Na Moją Osiemnastkę",
    imageUrl: "https://i.ibb.co/Ky5N1fV/ewa.jpg",
  },
  {
    id: 1,
    category: ["rocznica"],
    title: "Tort na rocznice ślubu",
    imageUrl: "https://i.ibb.co/sgxPRz8/oplatek1.jpg",
  },
  {
    id: 2,
    category: ["owocowy"],
    title: "Tort owocowy",
    imageUrl: "https://i.ibb.co/S60RNHy/owocowe1.jpg",
  },
  {
    id: 3,
    category: ["sport"],
    title: "Tort dla tenisisty stołowego",
    imageUrl: "https://i.ibb.co/h9Kxv48/pingpong1.jpg",
  },
  {
    id: 4,
    category: ["dzieci", "zwierzęta"],
    title: "Tort dla fana ptaszków nr1",
    imageUrl: "https://i.ibb.co/6gP2mBR/ptaszki1.jpg",
  },
  {
    id: 5,
    category: ["zwierzęta", "nietypowy"],
    title: "Tort dla łowcy",
    imageUrl: "https://i.ibb.co/q1r77qJ/lowiecki1.jpg",
  },
  {
    id: 6,
    category: ["czekoladki"],
    title: "Tort czekoladkowy nr1",
    imageUrl: "https://i.ibb.co/G5hDdhc/czekoladki1.jpg",
  },
  {
    id: 7,
    category: ["urodziny"],
    title: "Tort dla Dżentelmena nr1",
    imageUrl: "https://i.ibb.co/T08NW00/dzentelmen1.jpg",
  },
  {
    id: 8,
    category: ["urodziny", "nietypowy"],
    title: "Tort dla fana piwa Tyskie",
    imageUrl: "https://i.ibb.co/NSmQTMM/piwo1.jpg",
  },
  {
    id: 9,
    category: ["urodziny", "dzieci"],
    title: "Tort Świnka nr1",
    imageUrl: "https://i.ibb.co/TBDz4Fh/swinka1.jpg",
  },
  {
    id: 10,
    category: ["urodziny", "rocznica"],
    title: "Tort dla Czterdziestolatki",
    imageUrl: "https://i.ibb.co/qnjcdFZ/tort40.jpg",
  },
  {
    id: 11,
    category: ["dzieci", "sport"],
    title: "Tort dla Piłkarza",
    imageUrl: "https://i.ibb.co/02yZww2/pilkarski1.jpg",
  },
  {
    id: 12,
    category: ["czekoladki"],
    title: "Tort Czekoladkowy nr2",
    imageUrl: "https://i.ibb.co/Rz15MHB/czekoladki2.jpg",
  },
  {
    id: 13,
    category: ["gracz", "dzieci"],
    title: "Tort Minecraft",
    imageUrl: "https://i.ibb.co/DD9RGTB/minecraft1.jpg",
  },
  {
    id: 14,
    category: ["urodziny", "rocznica"],
    title: "Tort Owocowy",
    imageUrl: "https://i.ibb.co/XLWNHCJ/owocowy2.jpg",
  },
  {
    id: 15,
    category: ["urodziny", "czekoladki"],
    title: "Tort na Osiemnastkę",
    imageUrl: "https://i.ibb.co/wLPfWnT/tort18.jpg",
  },
  {
    id: 16,
    category: ["dzieci", "gracz"],
    title: "Tort Gracza nr2",
    imageUrl: "https://i.ibb.co/h8vz3Nd/gracza2.jpg",
  },
  {
    id: 17,
    category: ["dzieci"],
    title: "Tort ze Słodyczy",
    imageUrl: "https://i.ibb.co/jwcLN9d/michasia.jpg",
  },
  {
    id: 18,
    category: ["urodziny"],
    title: "Tort Dla Solenizantki nr1",
    imageUrl: "https://i.ibb.co/BnkYNBb/frida.jpg",
  },
  {
    id: 19,
    category: ["dzieci", "gracz"],
    title: "Tort Gracza nr3",
    imageUrl: "https://i.ibb.co/bXBj39F/gracza3.jpg",
  },
  {
    id: 20,
    category: ["urodziny"],
    title: "Tort Czekoladkowy nr3",
    imageUrl: "https://i.ibb.co/5hT4WcS/czekoladki3.jpg",
  },
  {
    id: 21,
    category: ["dzieci", "nietypowy"],
    title: "Tort Świnka nr2",
    imageUrl: "https://i.ibb.co/7jZLzgm/swinka2.jpg",
  },
  {
    id: 22,
    category: ["dzieci"],
    title: "Tort Czerwonego Kapturka",
    imageUrl: "https://i.ibb.co/4R4GSTW/kapturek.jpg",
  },
  {
    id: 23,
    category: ["zwierzeta"],
    title: "Tort dla fana ptaszków nr2",
    imageUrl: "https://i.ibb.co/rF48C0j/ptaszki2.jpg",
  },
  {
    id: 24,
    category: ["urodziny"],
    title: "Tort Urodzinowy nr1",
    imageUrl: "https://i.ibb.co/1ZyBSPP/urodziny-Nr1.jpg",
  },
  {
    id: 25,
    category: ["dzieci", "gracz"],
    title: "Tort Gracza nr4",
    imageUrl: "https://i.ibb.co/HN9YSLc/gracza4.jpg",
  },
  {
    id: 26,
    category: ["dzieci", "gracz"],
    title: "Tort Gracza nr4",
    imageUrl: "https://i.ibb.co/HN9YSLc/gracza4.jpg",
  },
  {
    id: 27,
    category: ["urodziny"],
    title: "Tort Czekoladkowy nr4",
    imageUrl: "https://i.ibb.co/h9P1sGj/czekoladki4.jpg",
  },
  {
    id: 28,
    category: ["urodziny", "nietypowy"],
    title: "Tort Pistacjowy nr1",
    imageUrl: "https://i.ibb.co/55JCvX0/pistacjowy1.jpg",
  },
  {
    id: 29,
    category: ["gracz", "dzieci", "nietypowy"],
    title: "Tort Pokemon",
    imageUrl: "https://i.ibb.co/9wHx6gR/pokemon.jpg",
  },
  {
    id: 30,
    category: ["dzieci"],
    title: "Tort Monster High",
    imageUrl: "https://i.ibb.co/QJ3bR3s/monsterhigh1.jpg",
  },
  {
    id: 31,
    category: ["urodziny"],
    title: "Tort dla Dżentelmena nr2",
    imageUrl: "https://i.ibb.co/y5r2pb0/dzentelmen2.jpg",
  },
  {
    id: 32,
    category: ["urodziny", "nietypowy"],
    title: "Tort Budowlańca",
    imageUrl: "https://i.ibb.co/2c8mfBp/budowlaniec1.jpg",
  },
  {
    id: 33,
    category: ["urodziny"],
    title: "Tort Dżentelmena nr3",
    imageUrl: "https://i.ibb.co/bsZ7BHN/dzentelmen3.jpg",
  },
  {
    id: 34,
    category: ["urodziny"],
    title: "Tort Czekoladowy nr1",
    imageUrl: "https://i.ibb.co/MMySxjd/czekoladowy1.jpg",
  },
  {
    id: 35,
    category: ["rocznica"],
    title: "Tort Dla Solenizantki nr2",
    imageUrl: "https://i.ibb.co/fqH5ChK/tort18-2.jpg",
  },
  {
    id: 36,
    category: ["dzieci"],
    title: "Tort z Bajki nr1",
    imageUrl: "https://i.ibb.co/25s4gL3/sing.jpg",
  },
  {
    id: 37,
    category: ["dzieci"],
    title: "Tort Gracza nr5",
    imageUrl: "https://i.ibb.co/vwfnzdK/spiderman1.jpg",
  },
  {
    id: 38,
    category: ["dzieci"],
    title: "Tort Czekoladkowy nr5",
    imageUrl: "https://i.ibb.co/wp9hhzb/czekoladki5.jpg",
  },
  {
    id: 39,
    category: ["rocznica"],
    title: "Tort Oreo nr1",
    imageUrl: "https://i.ibb.co/BCrQdTN/oreo1.jpg",
  },
  {
    id: 40,
    category: ["rocznica", "nietypowy"],
    title: "Tort Lekarki nr1",
    imageUrl: "https://i.ibb.co/RTbr7ht/lekarka1.jpg",
  },
  {
    id: 41,
    category: ["urodziny", "nietypowy"],
    title: "Tort Rolnika",
    imageUrl: "https://i.ibb.co/4dCrrDc/traktor.jpg",
  },
  {
    id: 42,
    category: ["urodziny", "dzieci"],
    title: "Tort Świnka nr3",
    imageUrl: "https://i.ibb.co/PcFMghS/swinka3.jpg",
  },
  {
    id: 43,
    category: ["dzieci"],
    title: "Tort Farma",
    imageUrl: "https://i.ibb.co/kh9hBkt/farma.jpg",
  },
  {
    id: 44,
    category: ["nietypowy"],
    title: "Tort Dla Kucharza",
    imageUrl: "https://i.ibb.co/bHy2F90/garnek.jpg",
  },
  {
    id: 45,
    category: ["urodziny"],
    title: "Tort Kremowy nr1",
    imageUrl: "https://i.ibb.co/4tVWMzR/kremowy1.jpg",
  },
  {
    id: 46,
    category: ["zwierzeta"],
    title: "Tort z Koniem",
    imageUrl: "https://i.ibb.co/7rGNZyw/kon1.jpg",
  },
  {
    id: 47,
    category: ["dzieci", "nietypowy"],
    title: "Tort Lego",
    imageUrl: "https://i.ibb.co/jZKC2X3/lego1.jpg",
  },
  {
    id: 48,
    category: ["rocznica"],
    title: "Tort Kremowy nr2",
    imageUrl: "https://i.ibb.co/988bw5Y/kremowy2.jpg",
  },
  {
    id: 49,
    category: ["urodziny", "sport"],
    title: "Tort Piłkarski nr2",
    imageUrl: "https://i.ibb.co/0yBbVjN/pilkarski2.jpg",
  },
  {
    id: 50,
    category: ["gracz", "dzieci"],
    title: "Tort Fortnite",
    imageUrl: "https://i.ibb.co/L16f6mP/gracza5.jpg",
  },
  {
    id: 51,
    category: ["dzieci"],
    title: "Tort Z Króliczkiem",
    imageUrl: "https://i.ibb.co/Gdp7Q8d/kroliczek1.jpg",
  },
  {
    id: 52,
    category: ["urodziny"],
    title: "Tort Oreo nr2",
    imageUrl: "https://i.ibb.co/7jrkQ0G/oreo2.jpg",
  },
  {
    id: 53,
    category: ["urodziny"],
    title: "Tort Kremowy nr3",
    imageUrl: "https://i.ibb.co/jrvyHbb/kremowy3.jpg",
  },
  {
    id: 54,
    category: ["dzieci"],
    title: "Tort Zajączek",
    imageUrl: "https://i.ibb.co/fQ1tKpH/zajaczek.jpg",
  },
  {
    id: 55,
    category: ["rocznica", "nietypowy"],
    title: "Tort JagerMeister",
    imageUrl: "https://i.ibb.co/Qms1jVJ/jager1.jpg",
  },
  {
    id: 56,
    category: ["urodziny", "nietypowy"],
    title: "Tort dla Muzyka",
    imageUrl: "https://i.ibb.co/hC5Nscp/muzyk1.jpg",
  },
  {
    id: 57,
    category: ["nietypowy"],
    title: "Tort Johnie Walker",
    imageUrl: "https://i.ibb.co/XtxvcpR/walker.jpg",
  },
  {
    id: 58,
    category: ["nietypowy", "dzieci"],
    title: "Tort z Gwiezdnych Wojen",
    imageUrl: "https://i.ibb.co/GMsRr9P/starwars.jpg",
  },
  {
    id: 59,
    category: ["dzieci"],
    title: "Tort z Bajki Auta",
    imageUrl: "https://i.ibb.co/ZX6dsyC/auta.jpg",
  },
  {
    id: 60,
    category: ["dzieci"],
    title: "Tort z Harrego Pottera nr1",
    imageUrl: "https://i.ibb.co/r32x7Hb/harryp.jpg",
  },
  {
    id: 61,
    category: ["sport"],
    title: "Tort Piłkarski nr3",
    imageUrl: "https://i.ibb.co/JvgR1g1/pilkarski3.jpg",
  },
  {
    id: 62,
    category: ["dzieci", "gracz"],
    title: "Tort Gracza nr6",
    imageUrl: "https://i.ibb.co/c8VYDhW/roblox.jpg",
  },
  {
    id: 63,
    category: ["dzieci", "gracz"],
    title: "Tort - Strażak Sam",
    imageUrl: "https://i.ibb.co/xqkdwFx/strazak.jpg",
  },
  {
    id: 64,
    category: ["dzieci", "gracz"],
    title: "Tort z gry Chicken Gun",
    imageUrl: "https://i.ibb.co/6Jqmsdz/chickengun.jpg",
  },
  {
    id: 65,
    category: ["urodziny"],
    title: "Tort Kremowy nr4",
    imageUrl: "https://i.ibb.co/L8Y6ZpS/kremowy4.jpg",
  },
  {
    id: 66,
    category: ["dzieci"],
    title: "Tort z Harrego Pottera nr2",
    imageUrl: "https://i.ibb.co/rmsy6gT/harryp2.jpg",
  },
];
